import type { AssignedWorkEntity } from '../api/assigned-work.types'

export const assignedWorkList: AssignedWorkEntity[] = [
  {
    _entityName: 'AssignedWork',
    id: '1',
    title: '8 пробник Реанимация математика 19.05 самопроверка',
    type: 'test',
    attempt: 1,
    solveStatus: 'solved',
    solveDeadlineAt: new Date('2025-06-24T12:00:00Z'),
    solvedAt: null,
    checkStatus: 'not-checked',
    checkDeadlineAt: new Date('2025-06-30T12:00:00Z'),
    checkedAt: null,
    workId: 'work1',
    work: {
      _entityName: 'Work',
      id: 'work1',
      title: '8 пробник Реанимация математика 19.05 самопроверка',
      type: 'test',
      description: null,
      subjectId: 'subject1',
      subject: {
        _entityName: 'Subject',
        id: 'subject1',
        name: 'Профильная математика',
        color: '#FF5733',
        createdAt: new Date('2025-01-01T10:00:00Z'),
        updatedAt: null
      },
      createdAt: new Date('2025-05-01T10:00:00Z'),
      updatedAt: null
    },
    statusHistory: [],
    score: null,
    maxScore: 100,
    isArchivedByStudent: false,
    isArchivedByAssistants: false,
    isArchivedByMentors: false,
    createdAt: new Date('2025-06-01T10:00:00Z'),
    updatedAt: new Date('2025-06-01T10:00:00Z'),
    excludedTaskIds: [],
    studentCommentId: null,
    mainMentorCommentId: null,
    helperMentorCommentId: null,
    studentId: 'student1',
    student: {
      _entityName: 'User',
      id: 'student1',
      name: 'Иван Иванов',
      username: 'ivanov',
      email: 'abc@dd.de',
      role: 'student',
      telegramId: '123456789',
      telegramUsername: 'ivanov_telegram',
      isBlocked: false,
      isVerified: true,
      createdAt: new Date('2025-01-01T10:00:00Z'),
      updatedAt: null
    },
    mainMentorId: 'mentor1',
    mainMentor: {
      _entityName: 'User',
      id: 'mentor1',
      name: 'Мария Петрова',
      username: 'petrova',
      email: 'petrova@example.com',
      role: 'mentor',
      telegramId: '987654321',
      telegramUsername: 'petrova_telegram',
      isBlocked: false,
      isVerified: true,
      createdAt: new Date('2025-01-01T10:00:00Z'),
      updatedAt: null
    },
    helperMentorId: 'mentor2',
    helperMentor: {
      _entityName: 'User',
      id: 'mentor2',
      name: 'Алексей Смирнов',
      username: 'smirnov',
      email: 'smirnov@example.com',
      role: 'mentor',
      telegramId: '123456789',
      telegramUsername: 'smirnov_telegram',
      isBlocked: false,
      isVerified: true,
      createdAt: new Date('2025-01-01T10:00:00Z'),
      updatedAt: null
    }
  },
  {
    _entityName: 'AssignedWork',
    id: '4',
    title: 'Практическая работа по биологии',
    type: 'test',
    attempt: 1,
    solveStatus: 'not-solved',
    solveDeadlineAt: new Date('2025-07-20T12:00:00Z'),
    solvedAt: null,
    checkStatus: 'not-checked',
    checkDeadlineAt: new Date('2025-07-25T12:00:00Z'),
    checkedAt: null,
    workId: 'work4',
    work: {
      _entityName: 'Work',
      id: 'work4',
      title: 'Практическая работа по биологии',
      type: 'test',
      description: null,
      subjectId: 'subject4',
      subject: {
        _entityName: 'Subject',
        id: 'subject4',
        name: 'Биология',
        color: '#FF33A1',
        createdAt: new Date('2025-01-01T10:00:00Z'),
        updatedAt: null
      },
      createdAt: new Date('2025-07-05T10:00:00Z'),
      updatedAt: null
    },
    statusHistory: [],
    score: null,
    maxScore: 100,
    isArchivedByStudent: false,
    isArchivedByAssistants: false,
    isArchivedByMentors: false,
    createdAt: new Date('2025-07-10T10:00:00Z'),
    updatedAt: new Date('2025-07-10T10:00:00Z'),
    excludedTaskIds: [],
    studentCommentId: null,
    mainMentorCommentId: null,
    helperMentorCommentId: null,
    studentId: 'student4',
    student: {
      _entityName: 'User',
      id: 'student4',
      name: 'Сергей Петров',
      username: 'petrov',
      email: 'petrov@example.com',
      role: 'student',
      telegramId: '123456789',
      telegramUsername: 'petrov_telegram',
      isBlocked: false,
      isVerified: true,
      createdAt: new Date('2025-01-01T10:00:00Z'),
      updatedAt: null
    },
    mainMentorId: null,
    helperMentorId: null
  },
  {
    _entityName: 'AssignedWork',
    id: '2',
    title: 'Контрольная работа по физике',
    type: 'test',
    attempt: 1,
    solveStatus: 'not-solved',
    solveDeadlineAt: new Date('2025-07-01T12:00:00Z'),
    solvedAt: null,
    checkStatus: 'not-checked',
    checkDeadlineAt: new Date('2025-07-07T12:00:00Z'),
    checkedAt: null,
    workId: 'work2',
    work: {
      _entityName: 'Work',
      id: 'work2',
      title: 'Контрольная работа по физике',
      type: 'test',
      description: null,
      subjectId: 'subject2',
      subject: {
        _entityName: 'Subject',
        id: 'subject2',
        name: 'Физика',
        color: '#33FF57',
        createdAt: new Date('2025-01-01T10:00:00Z'),
        updatedAt: null
      },
      createdAt: new Date('2025-06-15T10:00:00Z'),
      updatedAt: null
    },
    statusHistory: [],
    score: null,
    maxScore: 100,
    isArchivedByStudent: false,
    isArchivedByAssistants: false,
    isArchivedByMentors: false,
    createdAt: new Date('2025-06-20T10:00:00Z'),
    updatedAt: new Date('2025-06-20T10:00:00Z'),
    excludedTaskIds: [],
    studentCommentId: null,
    mainMentorCommentId: null,
    helperMentorCommentId: null,
    studentId: 'student2',
    student: {
      _entityName: 'User',
      id: 'student2',
      name: 'Анна Сергеева',
      username: 'sergeeva',
      email: 'sergeeva@example.com',
      role: 'student',
      telegramId: '123456789',
      telegramUsername: 'sergeeva_telegram',
      isBlocked: false,
      isVerified: true,
      createdAt: new Date('2025-01-01T10:00:00Z'),
      updatedAt: null
    },
    mainMentorId: 'mentor3',
    mainMentor: {
      _entityName: 'User',
      id: 'mentor3',
      name: 'Светлана Иванова',
      username: 'ivanova',
      email: 'ivanova@example.com',
      role: 'mentor',
      telegramId: '123456789',
      telegramUsername: 'ivanova_telegram',
      isBlocked: false,
      isVerified: true,
      createdAt: new Date('2025-01-01T10:00:00Z'),
      updatedAt: null
    },
    helperMentorId: 'mentor4',
    helperMentor: {
      _entityName: 'User',
      id: 'mentor4',
      name: 'Дмитрий Кузнецов',
      username: 'kuznetsov',
      email: 'kuznetsov@example.com',
      role: 'mentor',
      telegramId: '123456789',
      telegramUsername: 'kuznetsov_telegram',
      isBlocked: false,
      isVerified: true,
      createdAt: new Date('2025-01-01T10:00:00Z'),
      updatedAt: null
    }
  },
  {
    _entityName: 'AssignedWork',
    id: '3',
    title: 'Лабораторная работа по химии',
    type: 'test',
    attempt: 1,
    solveStatus: 'solved',
    solveDeadlineAt: new Date('2025-07-10T12:00:00Z'),
    solvedAt: new Date('2025-07-05T10:00:00Z'),
    checkStatus: 'checked',
    checkDeadlineAt: new Date('2025-07-15T12:00:00Z'),
    checkedAt: new Date('2025-07-12T10:00:00Z'),
    workId: 'work3',
    work: {
      _entityName: 'Work',
      id: 'work3',
      title: 'Лабораторная работа по химии',
      type: 'test',
      description: null,
      subjectId: 'subject3',
      subject: {
        _entityName: 'Subject',
        id: 'subject3',
        name: 'Химия',
        color: '#3357FF',
        createdAt: new Date('2025-01-01T10:00:00Z'),
        updatedAt: null
      },
      createdAt: new Date('2025-06-25T10:00:00Z'),
      updatedAt: null
    },
    statusHistory: [],
    score: 85,
    maxScore: 100,
    isArchivedByStudent: false,
    isArchivedByAssistants: false,
    isArchivedByMentors: false,
    createdAt: new Date('2025-07-01T10:00:00Z'),
    updatedAt: new Date('2025-07-01T10:00:00Z'),
    excludedTaskIds: [],
    studentCommentId: null,
    mainMentorCommentId: null,
    helperMentorCommentId: null,
    studentId: 'student3',
    student: {
      _entityName: 'User',
      id: 'student3',
      name: 'Елена Васильева',
      username: 'vasilieva',
      email: 'vasilieva@example.com',
      role: 'student',
      telegramId: '123456789',
      telegramUsername: 'vasilieva_telegram',
      isBlocked: false,
      isVerified: true,
      createdAt: new Date('2025-01-01T10:00:00Z'),
      updatedAt: null
    },
    mainMentorId: 'mentor5',
    mainMentor: {
      _entityName: 'User',
      id: 'mentor5',
      name: 'Ольга Смирнова',
      username: 'smirnova',
      email: 'smirnova@example.com',
      role: 'mentor',
      telegramId: '123456789',
      telegramUsername: 'smirnova_telegram',
      isBlocked: false,
      isVerified: true,
      createdAt: new Date('2025-01-01T10:00:00Z'),
      updatedAt: null
    },
    helperMentorId: null
  }
]
