<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 48 48"
  >
    <defs>
      <radialGradient
        id="firefox-body"
        cx="34%"
        cy="76%"
        r="80%"
      >
        <stop
          offset="0%"
          stop-color="#FFF44F"
        />
        <stop
          offset="35%"
          stop-color="#FF9500"
        />
        <stop
          offset="75%"
          stop-color="#F5203F"
        />
        <stop
          offset="100%"
          stop-color="#E31587"
        />
      </radialGradient>
      <linearGradient
        id="firefox-tail"
        x1="0"
        y1="0"
        x2="1"
        y2="1"
      >
        <stop
          offset="0%"
          stop-color="#00C8D7"
        />
        <stop
          offset="45%"
          stop-color="#7542E5"
        />
        <stop
          offset="100%"
          stop-color="#B5007F"
        />
      </linearGradient>
      <mask id="firefox-crescent">
        <circle
          cx="24"
          cy="24"
          r="24"
          fill="#FFFFFF"
        />
        <circle
          cx="29"
          cy="29"
          r="21"
          fill="#000000"
        />
      </mask>
    </defs>
    <circle
      cx="24"
      cy="24"
      r="24"
      fill="url(#firefox-body)"
    />
    <rect
      width="48"
      height="48"
      fill="url(#firefox-tail)"
      mask="url(#firefox-crescent)"
    />
  </svg>
</template>
