import type { UserEntity } from '../api/user.types'

const users: UserEntity[] = [
  {
    _entityName: 'User',
    id: '1',
    createdAt: new Date('2025-05-01T10:00:00Z'),
    updatedAt: null,
    username: 'jdoe',
    email: 'jdoe@example.com',
    name: 'John Doe',
    telegramId: '123456789',
    telegramUsername: 'johndoe',
    role: 'admin',
    isBlocked: false,
    isVerified: true
  },
  {
    _entityName: 'User',
    id: '2',
    createdAt: new Date('2025-05-02T11:30:00Z'),
    updatedAt: new Date('2025-06-01T08:00:00Z'),
    username: 'asmith',
    email: 'asmith@example.com',
    name: 'Alice Smith',
    telegramId: null,
    telegramUsername: null,
    role: 'teacher',
    isBlocked: false,
    isVerified: true
  },
  {
    _entityName: 'User',
    id: '3',
    createdAt: new Date('2025-05-03T09:45:00Z'),
    updatedAt: null,
    username: 'bwong',
    email: 'bwong@example.com',
    name: 'Ben Wong',
    telegramId: '987654321',
    telegramUsername: 'bwong123',
    role: 'student',
    isBlocked: false,
    isVerified: false
  },
  {
    _entityName: 'User',
    id: '4',
    createdAt: new Date('2025-05-04T14:22:00Z'),
    updatedAt: null,
    username: 'lchen',
    email: 'lchen@example.com',
    name: 'Lily Chen',
    telegramId: null,
    telegramUsername: null,
    role: 'mentor',
    isBlocked: false,
    isVerified: true
  },
  {
    _entityName: 'User',
    id: '5',
    createdAt: new Date('2025-05-05T16:00:00Z'),
    updatedAt: new Date('2025-06-01T10:00:00Z'),
    username: 'dlee',
    email: 'dlee@example.com',
    name: 'Daniel Lee',
    telegramId: '192837465',
    telegramUsername: 'danlee',
    role: 'assistant',
    isBlocked: false,
    isVerified: false
  },
  {
    _entityName: 'User',
    id: '6',
    createdAt: new Date('2025-05-06T13:10:00Z'),
    updatedAt: null,
    username: 'mroberts',
    email: 'mroberts@example.com',
    name: 'Mia Roberts',
    telegramId: null,
    telegramUsername: null,
    role: 'student',
    isBlocked: true,
    isVerified: false
  },
  {
    _entityName: 'User',
    id: '7',
    createdAt: new Date('2025-05-07T08:00:00Z'),
    updatedAt: null,
    username: 'kpatel',
    email: 'kpatel@example.com',
    name: 'Kiran Patel',
    telegramId: '555123456',
    telegramUsername: 'kiran_p',
    role: 'mentor',
    isBlocked: false,
    isVerified: true
  },
  {
    _entityName: 'User',
    id: '8',
    createdAt: new Date('2025-05-08T15:15:00Z'),
    updatedAt: null,
    username: 'tsanders',
    email: 'tsanders@example.com',
    name: 'Tina Sanders',
    telegramId: '777888999',
    telegramUsername: 'tinas',
    role: 'assistant',
    isBlocked: false,
    isVerified: true
  },
  {
    _entityName: 'User',
    id: '9',
    createdAt: new Date('2025-05-09T12:25:00Z'),
    updatedAt: null,
    username: 'wgrant',
    email: 'wgrant@example.com',
    name: 'Will Grant',
    telegramId: null,
    telegramUsername: null,
    role: 'teacher',
    isBlocked: false,
    isVerified: false
  },
  {
    _entityName: 'User',
    id: '10',
    createdAt: new Date('2025-05-10T09:00:00Z'),
    updatedAt: new Date('2025-06-10T07:30:00Z'),
    username: 'jkim',
    email: 'jkim@example.com',
    name: 'Jenny Kim',
    telegramId: '888777666',
    telegramUsername: 'jenny_k',
    role: 'student',
    isBlocked: false,
    isVerified: true
  },
  {
    _entityName: 'User',
    id: '11',
    createdAt: new Date('2025-05-11T07:50:00Z'),
    updatedAt: null,
    username: 'fnguyen',
    email: 'fnguyen@example.com',
    name: 'Frank Nguyen',
    telegramId: null,
    telegramUsername: null,
    role: 'mentor',
    isBlocked: false,
    isVerified: false
  },
  {
    _entityName: 'User',
    id: '12',
    createdAt: new Date('2025-05-12T10:10:00Z'),
    updatedAt: null,
    username: 'rcastro',
    email: 'rcastro@example.com',
    name: 'Rosa Castro',
    telegramId: '111222333',
    telegramUsername: 'rosac',
    role: 'admin',
    isBlocked: false,
    isVerified: true
  },
  {
    _entityName: 'User',
    id: '13',
    createdAt: new Date('2025-05-13T12:00:00Z'),
    updatedAt: null,
    username: 'hzhou',
    email: 'hzhou@example.com',
    name: 'Helen Zhou',
    telegramId: null,
    telegramUsername: null,
    role: 'assistant',
    isBlocked: true,
    isVerified: false
  },
  {
    _entityName: 'User',
    id: '14',
    createdAt: new Date('2025-05-14T17:45:00Z'),
    updatedAt: new Date('2025-06-01T11:15:00Z'),
    username: 'btaylor',
    email: 'btaylor@example.com',
    name: 'Brian Taylor',
    telegramId: '666555444',
    telegramUsername: 'briant',
    role: 'student',
    isBlocked: false,
    isVerified: true
  },
  {
    _entityName: 'User',
    id: '15',
    createdAt: new Date('2025-05-15T06:30:00Z'),
    updatedAt: null,
    username: 'egarcia',
    email: 'egarcia@example.com',
    name: 'Elena Garcia',
    telegramId: '222333444',
    telegramUsername: 'elena_g',
    role: 'teacher',
    isBlocked: false,
    isVerified: true
  }
]

export { users }
