import type { SubjectEntity } from "@/modules/subjects/api/subject.types"
import type { WorkEntity } from "../api/work.types"

const subjects: SubjectEntity[] = [
  {
    id: 'sub1',
    name: 'Математика',
    color: '#FF6B6B',
    createdAt: new Date('2025-04-01T10:00:00Z'),
    updatedAt: null,
  },
  {
    id: 'sub2',
    name: 'Физика',
    color: '#4ECDC4',
    createdAt: new Date('2025-04-02T10:00:00Z'),
    updatedAt: null,
  },
  {
    id: 'sub3',
    name: 'Химия',
    color: '#FFD93D',
    createdAt: new Date('2025-04-03T10:00:00Z'),
    updatedAt: null,
  },
  {
    id: 'sub4',
    name: 'Биология',
    color: '#A29BFE',
    createdAt: new Date('2025-04-04T10:00:00Z'),
    updatedAt: null,
  },
  {
    id: 'sub5',
    name: 'Литература',
    color: '#FF9F1C',
    createdAt: new Date('2025-04-05T10:00:00Z'),
    updatedAt: null,
  },
]

const works: WorkEntity[] = [
  {
    id: 'work1',
    createdAt: new Date('2025-06-01T08:00:00Z'),
    updatedAt: null,
    title: 'Тест по основам алгебры',
    type: 'test',
    description: 'Линейные уравнения и неравенства',
    subjectId: 'sub1',
    subject: subjects[0],
  },
  {
    id: 'work2',
    createdAt: new Date('2025-06-02T08:00:00Z'),
    updatedAt: null,
    title: 'Мини-тест по законам Ньютона',
    type: 'mini-test',
    description: 'Быстрая проверка по механике',
    subjectId: 'sub2',
    subject: subjects[1],
  },
  {
    id: 'work3',
    createdAt: new Date('2025-06-03T08:00:00Z'),
    updatedAt: null,
    title: 'Фразы по органической химии',
    type: 'phrase',
    description: 'Ключевые термины и реакции',
    subjectId: 'sub3',
    subject: subjects[2],
  },
  {
    id: 'work4',
    createdAt: new Date('2025-06-04T08:00:00Z'),
    updatedAt: null,
    title: 'Пробная работа по фотосинтезу',
    type: 'trial-work',
    description: 'Лабораторная симуляция дыхания растений',
    subjectId: 'sub4',
    subject: subjects[3],
  },
  {
    id: 'work5',
    createdAt: new Date('2025-06-05T08:00:00Z'),
    updatedAt: null,
    title: 'Разбор «Макбета»',
    type: 'second-part',
    description: 'Анализ развития персонажа',
    subjectId: 'sub5',
    subject: subjects[4],
  },
  {
    id: 'work6',
    createdAt: new Date('2025-06-06T08:00:00Z'),
    updatedAt: null,
    title: 'Тест по квадратным уравнениям',
    type: 'test',
    description: 'Стандартная форма, разложение, выделение квадрата',
    subjectId: 'sub1',
    subject: subjects[0],
  },
  {
    id: 'work7',
    createdAt: new Date('2025-06-07T08:00:00Z'),
    updatedAt: null,
    title: 'Мини-тест по кинематике',
    type: 'mini-test',
    description: 'Движение в одном и двух измерениях',
    subjectId: 'sub2',
    subject: subjects[1],
  },
  {
    id: 'work8',
    createdAt: new Date('2025-06-08T08:00:00Z'),
    updatedAt: null,
    title: 'Фразы по кислотам и основаниям',
    type: 'phrase',
    description: null,
    subjectId: 'sub3',
    subject: subjects[2],
  },
  {
    id: 'work9',
    createdAt: new Date('2025-06-09T08:00:00Z'),
    updatedAt: null,
    title: 'Пробная работа по строению клетки',
    type: 'trial-work',
    description: 'Микроскопическое исследование органелл',
    subjectId: 'sub4',
    subject: subjects[3],
  },
  {
    id: 'work10',
    createdAt: new Date('2025-06-10T08:00:00Z'),
    updatedAt: null,
    title: 'Сравнительный анализ поэзии',
    type: 'second-part',
    description: 'Сравнение современной и романтической поэзии',
    subjectId: 'sub5',
    subject: subjects[4],
  },
  {
    id: 'work11',
    createdAt: new Date('2025-06-11T08:00:00Z'),
    updatedAt: null,
    title: 'Тест по логарифмам',
    type: 'test',
    description: null,
    subjectId: 'sub1',
    subject: subjects[0],
  },
  {
    id: 'work12',
    createdAt: new Date('2025-06-12T08:00:00Z'),
    updatedAt: null,
    title: 'Мини-тест по энергии',
    type: 'mini-test',
    description: 'Формулы работы и энергии',
    subjectId: 'sub2',
    subject: subjects[1],
  },
  {
    id: 'work13',
    createdAt: new Date('2025-06-13T08:00:00Z'),
    updatedAt: null,
    title: 'Фразы по периодической таблице',
    type: 'phrase',
    description: 'Элементы и тенденции',
    subjectId: 'sub3',
    subject: subjects[2],
  },
  {
    id: 'work14',
    createdAt: new Date('2025-06-14T08:00:00Z'),
    updatedAt: null,
    title: 'Пробная работа по генетике',
    type: 'trial-work',
    description: 'Скрещивание и вероятность наследования',
    subjectId: 'sub4',
    subject: subjects[3],
  },
  {
    id: 'work15',
    createdAt: new Date('2025-06-15T08:00:00Z'),
    updatedAt: null,
    title: 'Эссе по театральным техникам',
    type: 'second-part',
    description: 'Анализ выразительных средств в пьесах',
    subjectId: 'sub5',
    subject: subjects[4],
  },
]

export { works }
